version: "3"
include:
  - proxy.yaml

x-env_file: &env_file
  env_file:
    - .env

services:
  mysql:
    image: mysql:8
    command: "--default-authentication-plugin=mysql_native_password"
    restart: on-failure
    volumes:
      - db_data:/var/lib/mysql
    <<: [*env_file]
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=db1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_HOST="%"
    ports:
      - 3306:3306
    networks:
      backend:
        ipv4_address: 172.20.0.10

  web-python:
    build:
      context: .
      dockerfile: Dockerfile.python
    restart: on-failure
    container_name: web-python
    environment:
      - DB_NAME=db1
      - DB_USER=root
      - DB_PASSWORD=12345
      - DB_HOST=mysql
#    ports:
#      - 5000:5000
    volumes:
      - registry_data:/data
    networks:
      backend:
        ipv4_address: 172.20.0.5

volumes:
  registry_data: {}
  db_data: {}

networks:
  backend:
    driver: bridge
    ipam:
    #  driver: default
      config:
        - subnet: 172.20.0.0/24
