FROM python:3.9-slim

RUN mkdir /code
WORKDIR /code
COPY requirements.txt .
RUN pip install --user -r requirements.txt
COPY main.py .
EXPOSE 5000
ENV PYTHONPATH="$PYTHONPATH:/code"
CMD ["python", "/code/main.py"]
